Mark the Container class TOOLKIT_DLLPUBLIC so that sfx2 builds on Win32 without an undefined reference to public: virtual bool __thiscall layoutimpl::Container::emptyVisible(void).
* patches/dev300/layoutdialogs2-development.diff
(toolkit/source/layout/core/container.hxx): Mark the Container
class TOOLKIT_DLLPUBLIC so that sfx2 builds on Win32 without an
undefined reference to public: virtual bool __thiscall
layoutimpl::Container::emptyVisible(void).